"""Add indexes and convert is_on_the_way to boolean

Revision ID: 875a426a6dcc
Revises: eef19e28d345
Create Date: 2026-09-17 11:15:15.875601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875a426a6dcc'
down_revision: Union[str, Sequence[str], None] = 'eef19e28d345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shop_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('salary_amount', sa.Float(), nullable=True),
        sa.Column('join_date', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    
    op.create_table('expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shop_id', sa.Integer(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)

    op.create_index(op.f('ix_employees_shop_id'), 'employees', ['shop_id'], unique=False)
    op.create_index(op.f('ix_expenses_shop_id'), 'expenses', ['shop_id'], unique=False)
    op.create_index(op.f('ix_expenses_timestamp'), 'expenses', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_shop_id'), 'inventory_transactions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_timestamp'), 'inventory_transactions', ['timestamp'], unique=False)
    op.execute("ALTER TABLE products ALTER COLUMN is_on_the_way DROP DEFAULT")
    op.execute("ALTER TABLE products ALTER COLUMN is_on_the_way TYPE BOOLEAN USING is_on_the_way::integer::boolean")
    op.execute("ALTER TABLE products ALTER COLUMN is_on_the_way SET DEFAULT false")
    op.drop_constraint(op.f('products_product_code_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_index(op.f('ix_products_shop_id'), 'products', ['shop_id'], unique=False)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_shop_id'), 'sales', ['shop_id'], unique=False)
    op.create_index(op.f('ix_sales_timestamp'), 'sales', ['timestamp'], unique=False)
    op.create_index(op.f('ix_shops_owner_id'), 'shops', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shops_owner_id'), table_name='shops')
    op.drop_index(op.f('ix_sales_timestamp'), table_name='sales')
    op.drop_index(op.f('ix_sales_shop_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index(op.f('ix_products_shop_id'), table_name='products')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.create_unique_constraint(op.f('products_product_code_key'), 'products', ['product_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'is_on_the_way',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_inventory_transactions_timestamp'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_shop_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_expenses_timestamp'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_shop_id'), table_name='expenses')
    op.drop_index(op.f('ix_employees_shop_id'), table_name='employees')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
