"""Add User Profile fields

Revision ID: ac32c8944027
Revises: 875a426a6dcc
Create Date: 2026-09-17 11:32:50.395006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac32c8944027'
down_revision: Union[str, Sequence[str], None] = '875a426a6dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('business_category', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('store_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'store_address')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'business_category')
    op.drop_column('users', 'business_name')
    # ### end Alembic commands ###
